#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


security:
  authentication:
    # Authentication types (supported types: PASSWORD,LDAP,CASDOOR_SSO,KEYCLOAK_SSO)
    type: KEYCLOAK_SSO
    keycloak:
      user:
        # 设置管理员用户名，该用户将被赋予ADMIN权限
        admin: admin
      default:
        # 设置默认租户，新用户将被分配到该租户
        tenant: root
frontend:
  home:
    path: /
keycloak:
  auth-server-url: http://keycloak.datahinge.com
  realm: portal
  resource: dolphinscheduler
  credentials:
    secret: iyM9bRbbRBODhcGI2H92eihUIGXJO1Mg
  redirect-uri: "http://localhost:5173/login"
#  redirect-uri: "http://192.168.133.102:5173/dolphinscheduler/ui/login"